# Generated by Django 4.2.9 on 2024-01-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
